name: Validate Merge Source

on:
  pull_request:
    branches:
      - main
      - developer

jobs:
  check-merge-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from allowed branch
        run: |
          BASE_BRANCH="${{ github.base_ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"

          if [[ "$BASE_BRANCH" == "main" && "$HEAD_BRANCH" != "developer" ]]; then
            echo "Only 'developer' branch can merge into 'main'."
            exit 1
          fi

          if [[ "$BASE_BRANCH" == "developer" && "$HEAD_BRANCH" != "developer-alessandra" && "$HEAD_BRANCH" != "developer-fabricio" ]]; then
            echo "Only 'developer-alessandra' or 'developer-fabricio' can merge into 'developer'."
            exit 1
          fi

          echo "Merge allowed."
